export const DEPARTMENTS = [
  "ARTIFICIAL INTELLIGENCE",
  "COMPUTER SCIENCE",
  "INFORMATION TECHNOLOGY",
  "CYBER SECURITY",
  "AGRICULTURE",
  "MECHANICAL",
  "ELECTRONICS AND COMMUNICATION ENGINEERING",
  "BIO MEDICAL ENGINEERING"
];

export const ACADEMIC_YEARS = [
  "1st year",
  "2nd year",
  "3rd year",
  "4th year"
];
